name: Update Gamescope Commit

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
    branches:
      - master
      
jobs:
  update-gamescope:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Latest Commit
        id: get-commit
        run: |
          latest_commit=$(curl -s https://api.github.com/repos/ValveSoftware/gamescope/commits/master | jq -r '.sha')
          echo "latest-commit=$latest_commit" >> $GITHUB_OUTPUT

      - name: Get Current Commit
        id: get-current-commit
        run: |
          current_commit=$(grep -oP '(?<=^%global commit ).*' gamescope/gamescope.spec)
          echo "current-commit=$current_commit" >> $GITHUB_OUTPUT

      - name: Compare Commits
        id: compare-commits
        run: |
          if [ "${{ steps.get-commit.outputs.latest-commit }}" != "${{ steps.get-current-commit.outputs.current-commit }}" ]; then
            echo "There is a new commit avaliable."
          else
            echo "There is no new commit avaliable."
            exit 1
          fi

      - name: Update Spec File
        if: steps.compare-commits.outcome == 'success'
        run: |
          sed -i "s/%global commit .*/%global commit ${{ steps.get-commit.outputs.latest_commit }}/g" gamescope/gamescope.spec

      - name: Commit and Push Changes
        if: steps.compare-commits.outcome == 'success'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add gamescope/gamescope.spec
          git commit -m "gamescope: Update commit to $latest_commit"
          git push
